# Generated by Django 5.1.7 on 2025-04-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_accountactivity"),
        ("accounts", "0005_userprofile_address"),
    ]

    operations = []
