# Generated by Django 5.1.7 on 2025-04-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_0004_accountactivity_0005_userprofile_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "min_investment",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "expected_return",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
